export const EXCEPTION_USER_NOT_FOUND = 'EXCEPTION_USER_NOT_FOUND';
export const EXCEPTION_BAD_DATA = 'EXCEPTION_BAD_DATA';
export const EXCEPTION_INTERNAL_SERVER_ERROR = 'EXCEPTION_INTERNAL_SERVER_ERROR';
